### ISSUE TITLE
This is awesome! Perhaps support all the Math.* functions?

### ISSUE THREAD

**Issue by trusktr** [rclai/meteor-reactive-number#1]
So instead of

``` js
number.calculate(function (number) {
  return Math.sqrt(number); // 5
});
```

we can do

``` js
number.sqrt() // 5
```

That would apply to all the `Math.*` functions that take a single number argument. That'd be awesome!!!

**Comment by rclai** [comment]
That would be cool!

**Comment by rclai** [comment]
Check it out.

**Comment by trusktr** [comment]
Aaaw, that's so awesome! With chaining too! Niiiiice!!

**Comment by trusktr** [comment]
I'll add to all my apps. It will be _so_ handy! :+1:
